
---
server:
  port: 8080
  #contextPath: /
  session:
    timeout: 10
---

#logging:
#  level:
#    org.springframework.web: ERROR
#    com.websystique.springboot: DEBUG
#  pattern:
#    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
#    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: E:/logs/log.log
---
spring:
  profiles: local
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      dialect: org.hibernate.dialect.MySQLDialect
---

spring:
  profiles: prod
  

#logging:
  #config: classpath:logback.xml
  #level:
    #ch.qos.logback.classic: DEBUG
    #org.hibernate: INFO
    #org.springframework.web: INFO
    #com.websystique.springboot: DEBUG

datasource:
  sampleapp:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:postgresql://localhost:5432/strapi
    username: postgres
    password: adminadmin
    #username: root
    #password: 
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      #dialect: org.hibernate.dialect.MySQLDialect
      
      

